[build-system]
requires = ["setuptools >= 61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "polysolve"
authors = [{name = "Matt Jones", email = "matt.jones@stfc.ac.uk"}]
requires-python = ">= 3.8"
readme = "README.md"
description = ""
license = {text = "MIT"}

keywords = []
dependencies = ["numpy"]
classifiers = []
dynamic = ["version"]

[project.urls]
Homepage="https://github.com/mJonesSTFC/project-training/polysolve"
Repository="https://github.com/mJonesSTFC/project-training.git"

[tool.setuptools.dynamic]
version = {attr = "polysolve.__version__"}
